remote_theme: thagler/thagler.github.io
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Tobby Hagler
description: The personal website of Tobby Hagler; engineering director and author
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]
