remote_theme: thagler/thagler.github.io
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Tobby Hagler
# description: The personal website of Tobby Hagler; engineering director and author
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]

# Includes an icon in the footer for each username you enter
footer-links:
  # dribbble:
  email: tobby@tobbyhagler.com
  # facebook:
  # flickr:
  github: thagler
  instagram: thagler
  linkedin: tobbyhagler
  #rss: rss
  bluesky: thagler.bsky.social
  # stackoverflow: 
  # youtube: # channel/<your_long_string> or user/<user-name>
  # googleplus: # anything in your profile username that comes after plus.google.com/
  # playconsole:
  # mastodon: # <your-mastodon-instance>/@<your-user-name> eg. fosstodon.org/@username
