remote_theme: BDHU/minimalist
plugins:
title: Tobby Hagler
description: The personal website of Tobby Hagler; engineering director and author
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Optional settings for the theme
author:
  name: Tobby Hagler
  email: your@email.com

# Color scheme (automatic by default)
color_scheme: dark  # options: light, dark, auto

# Includes an icon in the footer for each username you enter
footer-links:
  # dribbble:
  email: tobby@tobbyhagler.com
  # facebook:
  # flickr:
  github: thagler
  instagram: thagler
  linkedin: tobbyhagler
  #rss: rss
  bluesky: thagler.bsky.social
  # stackoverflow: 
  # youtube: # channel/<your_long_string> or user/<user-name>
  # googleplus: # anything in your profile username that comes after plus.google.com/
  # playconsole:
  # mastodon: # <your-mastodon-instance>/@<your-user-name> eg. fosstodon.org/@username
